# Configuración de la moneda por defecto
id: "default"
name: "monedas"
name-singular: "moneda"
symbol: "$"
decimal: true
starting-balance: 100.0
max-balance: 999999999.99
min-transfer: 0.01
max-transfer: 100000.0
enabled: true