name: MythicEconomy
version: '${version}'
main: com.spectrasonic.MythicEconomy.Main
api-version: '1.21'
authors: [Spectrasonic]
description: "Sistema de economía completo para servidores de Minecraft con API para desarrolladores"
website: https://github.com/spectrasonic
depend: ["Vault", "PlaceholderAPI"]

# API Information for other plugins
provides:
  - MythicEconomyAPI


commands:
  economy:
    permission: MythicEconomy.economy.admin
    aliases: [eco, econ]
  
  money:
    permission: MythicEconomy.money
    aliases: [balance, bal]
  
  pay:
    permission: MythicEconomy.pay
    aliases: [send]

permissions:
  MythicEconomy.*:
    description: "Acceso completo a MythicEconomy"
    default: op
    children:
      MythicEconomy.economy.admin:
        default: op
      MythicEconomy.money:
        default: true
      MythicEconomy.pay:
        default: true
  
  MythicEconomy.economy.admin:
    description: "Permite usar todos los comandos de administración"
    default: op
    children:
      MythicEconomy.economy.give:
        default: op
      MythicEconomy.economy.take:
        default: op
      MythicEconomy.economy.set:
        default: op
      MythicEconomy.economy.balance.others:
        default: op
      MythicEconomy.economy.reload:
        default: op
