name: MythicEconomy
api: "1.21"
version: "${version}"
main: com.spectrasonic.MythicEconomy.Main
api-version: "1.21"
authors: [Spectrasonic]
description: "Sistema de economía completo para servidores de Minecraft con API para desarrolladores"
website: https://github.com/spectrasonic
depend: ["Vault", "PlaceholderAPI"]

# API Information for other plugins
provides:
    - MythicEconomyAPI

commands:
    economy:
        permission: MythicEconomy.economy.admin
        aliases: [eco, econ]

permissions:
    MythicEconomy.economy.admin:
        default: op
    MythicEconomy.economy.give:
        default: op
    MythicEconomy.economy.take:
        default: op
    MythicEconomy.economy.set:
        default: op
    MythicEconomy.economy.balance.others:
        default: op
    MythicEconomy.economy.reload:
        default: op
    MythicEconomy.money:
        default: true
    MythicEconomy.pay:
        default: true
